/**
 * Improvisation: vamps and voicings.
 *
 * THE RULE THAT MAKES THIS TEACH RATHER THAN DECORATE:
 * every chord in every vamp is built ONLY from notes the scale actually contains.
 * If a progression would need a note we removed, it does not exist here. That is
 * the whole lesson — four triads and three seventh-chord sets is not a shortage,
 * it is the harmonic world this scale lives in.
 *
 * Progressions are therefore derived from the scale at runtime, by scale degree,
 * never hardcoded per key. One definition works in all twelve.
 */

import { Note, note, pc, midi, noteName } from "./note";
import { ScaleInstance } from "./scales";
import { findChords, tertianOnly, ChordSet } from "./chords";

export type VoicingStyle = "shell" | "rootless" | "quartal" | "spread";

export interface VoicedChord {
  label: string;
  altLabel?: string;
  bass: number;          // midi
  voicing: number[];     // midi, ascending
  chordTones: number[];  // pitch classes sounding — used to light the ring
  degreeRoot: number;    // which scale degree the chord is built on
}

export interface VampStep {
  chord: VoicedChord;
  bars: number;
}

export interface VampDef {
  id: string;
  name: string;
  description: string;
  /** scale degrees (0-indexed) the chords are built on */
  degrees: number[];
  barsEach: number;
  /** which modes this makes sense in; empty = any */
  modes?: number[];
  feel: "straight" | "swing" | "68";
}

/** Progressions by scale degree. Because the harmony of a hexatonic is small, the
 *  interesting vamps are the ones that move between its few chords slowly. */
export const VAMPS: VampDef[] = [
  {
    id: "drone", name: "Drone", feel: "straight", degrees: [0], barsEach: 4,
    description:
      "Tonic only. The oldest way to learn a scale — nothing to navigate, so you hear each note against the root.",
  },
  {
    id: "tonic", name: "Tonic vamp", feel: "straight", degrees: [0], barsEach: 2,
    description:
      "One chord, comped. Every note of the scale is a chord tone over it, which is the point.",
  },
  {
    id: "i-vi", name: "I – vi", feel: "straight", degrees: [0, 4], barsEach: 2,
    description: "Two chords a third apart. The gentlest possible motion.",
  },
  {
    id: "turnaround", name: "Four-chord turnaround", feel: "straight",
    degrees: [0, 4, 2, 3], barsEach: 1,
    description:
      "All four available triads, in order. In the Ionian/Lydian mode that is I–vi–iii–V — the whole harmonic vocabulary of the scale in four bars.",
  },
  {
    id: "i-VII", name: "i – ♭VII", feel: "straight", degrees: [0, 5], barsEach: 2,
    description: "Modal minor motion. Sits still and rocks.",
  },
  {
    id: "quartal", name: "Quartal", feel: "straight", degrees: [1, 3, 5], barsEach: 2,
    description:
      "Stacked fourths instead of thirds. This scale is unusually rich in them — the McCoy Tyner sound.",
  },
  {
    id: "gospel68", name: "6/8 rock", feel: "68", degrees: [0, 4, 3], barsEach: 2,
    description: "A slow 6/8 with the three strongest chords. Room to sing over.",
  },
  {
    id: "swing", name: "Swing two-feel", feel: "swing", degrees: [0, 2], barsEach: 2,
    description: "Swung, two chords, walking bass. For jazz phrasing practice.",
  },
];

export const vampById = (id: string) => VAMPS.find((v) => v.id === id) ?? VAMPS[0];

/** Stack scale degrees into a chord, wrapping the octave as we climb. */
function stackFromDegree(scale: Note[], degree: number, count: number, skip = 2): Note[] {
  const n = scale.length;
  const out: Note[] = [];
  for (let i = 0; i < count; i++) {
    const idx = degree + i * skip;
    const base = scale[((idx % n) + n) % n];
    out.push(note(base.letter, base.alt, base.octave + Math.floor(idx / n)));
  }
  return out;
}

/**
 * Build the chord ROOTED on a scale degree.
 *
 * ⚠️ THE TRAP THIS FUNCTION EXISTS TO AVOID — and I fell into it once:
 * you cannot build a triad in a hexatonic by taking "every other scale degree".
 * In C D E G A B that gives C–E–A, which is A minor, not C. Skipping two degrees
 * in a six-note scale yields a MIX of thirds and fourths — that is Theorem 5, the
 * app's own headline result. Chords must be looked up by real interval from the
 * scale's chord table, never generated by degree arithmetic.
 */
function chordOnDegree(scale: ScaleInstance, degree: number): ChordSet | null {
  const n = scale.notes.length;
  const rootName = noteName(scale.notes[((degree % n) + n) % n]);
  const all = findChords(scale.notes, [3, 4]);
  const rooted = (size: 3 | 4, tertian: boolean) =>
    all.find((c) =>
      c.size === size &&
      c.names.some((x) => x.root === rootName && (!tertian || x.family === "tertian"))
    );
  return rooted(4, true) ?? rooted(3, true) ?? rooted(4, false) ?? rooted(3, false) ?? null;
}

/** A chord's notes as an ascending stack from the given root. */
function ascendingFrom(chord: ChordSet, rootName: string, octave: number): Note[] {
  const named = chord.names.find((x) => x.root === rootName) ?? chord.names[0];
  const out: Note[] = [];
  let oct = octave, prev = -1;
  for (const nm of named.notes) {
    const src = chord.notes.find((x) => noteName(x) === nm);
    if (!src) continue;
    if (prev >= 0 && pc(src) <= prev) oct++;
    prev = pc(src);
    out.push(note(src.letter, src.alt, oct));
  }
  return out;
}

/**
 * Build a playable voicing on a scale degree.
 *  shell    — root, 3rd and 7th. The jazz default.
 *  rootless — drop the root and let the bass own it (Bill Evans "A").
 *  quartal  — stacked fourths. Generated by stepping THREE degrees, which in a
 *             hexatonic is perfect every time. This scale's signature colour.
 *  spread   — the whole chord, wide, for slow feels.
 */
export function voiceDegree(
  scale: ScaleInstance, degree: number, style: VoicingStyle, octave = 4
): VoicedChord {
  const n = scale.notes.length;
  const rootNote = scale.notes[((degree % n) + n) % n];
  const rootName = noteName(rootNote);
  const bass = midi(note(rootNote.letter, rootNote.alt, octave - 2));

  const chord = chordOnDegree(scale, degree);
  const quartalStack = stackFromDegree(scale.notes, degree, 4, 3);

  let tones: Note[];
  if (style === "quartal" || !chord) {
    tones = quartalStack;
  } else {
    const asc = ascendingFrom(chord, rootName, octave);
    tones =
      style === "shell"
        ? asc.filter((_, i) => i === 0 || i === 1 || i === asc.length - 1)
        : style === "rootless"
          ? (asc.length > 3 ? asc.slice(1) : asc)
          : asc;
  }

  const lifted = [...new Set(tones.map((t) => {
    let m = midi(note(t.letter, t.alt, t.octave + (octave - 4)));
    while (m < 55) m += 12;
    while (m > 84) m -= 12;
    return m;
  }))].sort((a, b) => a - b);

  const useChordLabel = chord && style !== "quartal";
  const named = useChordLabel
    ? [...chord!.names].sort((a, b) =>
        Number(b.root === rootName) - Number(a.root === rootName))
    : [];

  return {
    label: named[0]?.symbol ?? `${rootName} quartal`,
    altLabel: named[1]?.symbol,
    bass,
    voicing: lifted,
    chordTones: useChordLabel ? chord!.pcs : [...new Set(quartalStack.map(pc))],
    degreeRoot: ((degree % n) + n) % n,
  };
}


export function buildVamp(
  scale: ScaleInstance, vamp: VampDef, style: VoicingStyle
): VampStep[] {
  return vamp.degrees.map((d) => ({
    chord: voiceDegree(scale, d, style),
    bars: vamp.barsEach,
  }));
}

/** Which vamps make musical sense for this mode. A quartal vamp on a mode with no
 *  third is the point; a "i – ♭VII" on a major mode is not. */
export function vampsFor(scale: ScaleInstance): VampDef[] {
  const hasThird = scale.degrees.includes("3") || scale.degrees.includes("b3");
  const isMinor = scale.degrees.includes("b3");
  return VAMPS.filter((v) => {
    if (v.id === "i-VII") return isMinor;
    if (v.id === "turnaround") return hasThird;
    return true;
  });
}

/** Guide tones: which of the scale's notes are chord tones right now, and which
 *  are the colour notes that make the line move. Both are correct to play — the
 *  distinction is what to LAND on. */
export function guideTones(scale: ScaleInstance, chord: VoicedChord) {
  const chordPcs = new Set(chord.chordTones);
  return {
    chordTones: scale.notes.filter((x) => chordPcs.has(pc(x))),
    colourTones: scale.notes.filter((x) => !chordPcs.has(pc(x))),
  };
}
