/**
 * M1 GATE — the TypeScript engine must reproduce the Python engine exactly.
 *
 * The oracle is engine/verified.json, generated by engine/shadava_theory.py.
 * If these fail, nothing visual matters. Do not weaken an assertion to make it
 * pass; fix the engine or regenerate the oracle deliberately.
 */
import { describe, it, expect } from "vitest";
import verified from "../engine/verified.json";

import {
  note, pc, midi, noteName, vexKey, spell, intervalName,
  normalOrder, primeForm, intervalVector, forteName, TRITONE_FREE_HEXACHORDS,
} from "../src/lib/theory/note";
import {
  buildScale, buildDiatonic, omissionSurvey, DIATONIC_MODES, KEYS, MAJOR, FAMILIES,
} from "../src/lib/theory/scales";
import { findChords, tertianOnly, triadPair, augmentedPair } from "../src/lib/theory/chords";
import { buildPattern, skipCycle, ladder } from "../src/lib/theory/patterns";
import { solveResolution, resolutionGrid, GATIS, YATIS } from "../src/lib/theory/resolution";

/* ── note spelling ─────────────────────────────────────────────────────── */
describe("note spelling", () => {
  it("computes pitch class and midi", () => {
    expect(pc(note("C", 0, 4))).toBe(0);
    expect(midi(note("C", 0, 4))).toBe(60);
    expect(pc(note("B", 1, 4))).toBe(0);   // B# is pc 0
    expect(pc(note("C", -1, 4))).toBe(11); // Cb is pc 11
  });
  it("refuses triple accidentals", () => {
    expect(spell("C", 6)).toBeNull();      // would need C###
  });
  it("emits VexFlow keys in ASCII", () => {
    expect(vexKey(note("F", 1, 5))).toBe("f#/5");
    expect(vexKey(note("E", -1, 3))).toBe("eb/3");
  });
  it("names intervals by letter distance, so A4 is never called P4", () => {
    expect(intervalName(note("F", 0, 4), note("B", 0, 4))).toBe("A4");
    expect(intervalName(note("C", 0, 4), note("F", 0, 4))).toBe("P4");
    expect(intervalName(note("B", 0, 4), note("F", 0, 5))).toBe("d5");
  });
});

/* ── set-class analysis ────────────────────────────────────────────────── */
describe("set-class analysis", () => {
  it("uses span-first normal order, not a lexicographic minimum", () => {
    // {0,2,4,7,9,11}: the naive lexicographic answer is [0,1,3,5,8,10] (span 10),
    // the correct normal order is [0,2,4,5,7,9] (span 9).
    expect(normalOrder([0, 2, 4, 7, 9, 11])).toEqual([0, 2, 4, 5, 7, 9]);
  });
  it("identifies 6-32 with vector <143250> and zero tritones", () => {
    const pcs = [0, 2, 4, 7, 9, 11];
    expect(primeForm(pcs)).toEqual([0, 2, 4, 5, 7, 9]);
    expect(intervalVector(pcs)).toEqual([1, 4, 3, 2, 5, 0]);
    expect(forteName(pcs)).toContain("6-32");
  });
  it("6-32 is the UNIQUE hexachord with the maximum perfect-fourth content", () => {
    // Guards the /scales copy: the "five" is five ic5 DYADS in the set, which is
    // not the same thing as the six perfect intervals in the skip-three cycle.
    // Conflating the two is exactly the error this test exists to catch.
    const classes = new Map<string, number[]>();
    for (let a = 0; a < 12; a++)
      for (let b = a + 1; b < 12; b++)
        for (let c = b + 1; c < 12; c++)
          for (let d = c + 1; d < 12; d++)
            for (let e = d + 1; e < 12; e++)
              for (let f = e + 1; f < 12; f++) {
                const set = [a, b, c, d, e, f];
                classes.set(primeForm(set).join(","), intervalVector(set));
              }
    const max = Math.max(...[...classes.values()].map((v) => v[4]));
    const winners = [...classes].filter(([, v]) => v[4] === max).map(([k]) => k);
    expect(max).toBe(5);
    expect(winners).toEqual(["0,2,4,5,7,9"]);          // 6-32, and only 6-32

    const hexa = buildScale("C", "diatonic", 0);
    expect(intervalVector(hexa.pcs)[4]).toBe(5);        // five dyads in the SET
    const cycle = skipCycle(hexa.notes, 3);
    expect(Object.values(cycle.tally).reduce((x, y) => x + y, 0)).toBe(6); // six in the CYCLE
    expect(cycle.tally).toEqual({ P5: 3, P4: 3 });
  });

  it("finds exactly five tritone-free hexachord set classes", () => {
    const free = new Set<string>();
    for (let a = 0; a < 12; a++)
      for (let b = a + 1; b < 12; b++)
        for (let c = b + 1; c < 12; c++)
          for (let d = c + 1; d < 12; d++)
            for (let e = d + 1; e < 12; e++)
              for (let f = e + 1; f < 12; f++) {
                const s = [a, b, c, d, e, f];
                if (intervalVector(s)[5] === 0) free.add(primeForm(s).join(","));
              }
    expect([...free].sort()).toEqual([...TRITONE_FREE_HEXACHORDS].sort());
    expect(free.size).toBe(5);
  });
});

/* ── THEOREM 1 ─────────────────────────────────────────────────────────── */
describe("Theorem 1 — only the 4th and the 7th can be removed", () => {
  const rows = omissionSurvey("C");
  it("matches the verified omission survey exactly", () => {
    expect(rows.length).toBe(verified.omission_survey.length);
    rows.forEach((r, i) => {
      const v = verified.omission_survey[i];
      expect(r.removedDegree).toBe(v.removed_degree);
      expect(r.removedNote).toBe(v.removed_note);
      expect(r.notes).toEqual(v.notes);
      expect(r.primeForm).toEqual(v.prime_form);
      expect(r.intervalVector).toEqual(v.interval_vector);
      expect(r.tritones).toBe(v.tritones);
      expect(r.is632).toBe(v.is_6_32);
    });
  });
  it("only degrees 4 and 7 give a tritone-free hexachord", () => {
    const free = rows.filter((r) => r.tritones === 0).map((r) => r.removedDegree);
    expect(free).toEqual([4, 7]);
    expect(rows.filter((r) => r.is632).map((r) => r.removedDegree)).toEqual([4, 7]);
  });
});

/* ── THEOREM 2 ─────────────────────────────────────────────────────────── */
describe("Theorem 2 — one hexachord, six rotations", () => {
  it("C major-no-4, A minor-no-b6 and the G hexachord are the same set", () => {
    const cMajNo4 = buildScale("C", "diatonic", 0);
    const aMinNo6 = buildScale("A", "diatonic", 4);
    const gHex = buildDiatonic("G", MAJOR)!.slice(0, 6);
    const s = (ns: { letter: string; alt: number; octave: number }[]) =>
      [...new Set(ns.map((n) => pc(n as never)))].sort((a, b) => a - b).join(",");
    expect(s(cMajNo4.notes)).toBe(s(aMinNo6.notes));
    expect(s(cMajNo4.notes)).toBe(s(gHex));
  });
  it("names all six rotations without ever saying 'gospel' or 'Sunday'", () => {
    expect(DIATONIC_MODES.length).toBe(6);
    const blob = JSON.stringify(DIATONIC_MODES).toLowerCase();
    expect(blob).not.toContain("gospel scale");
    expect(blob).not.toContain("sunday");
  });
  it("mode 2 has no third and mode 6 has no fifth", () => {
    expect(DIATONIC_MODES[1].hasThird).toBe(false);
    expect(DIATONIC_MODES[5].hasFifth).toBe(false);
  });
});

/* ── multi-key spelling ────────────────────────────────────────────────── */
describe("multi-key spelling", () => {
  const EXPECTED: Record<string, string> = {
    C: "C D E G A B", G: "G A B D E F#", D: "D E F# A B C#", A: "A B C# E F# G#",
    E: "E F# G# B C# D#", B: "B C# D# F# G# A#", "F#": "F# G# A# C# D# E#",
    Db: "Db Eb F Ab Bb C", Ab: "Ab Bb C Eb F G", Eb: "Eb F G Bb C D",
    Bb: "Bb C D F G A", F: "F G A C D E",
  };
  it.each(KEYS)("spells %s correctly with no repeated letters", (k) => {
    const s = buildScale(k, "diatonic", 0);
    expect(s.error).toBeUndefined();
    expect(s.notes.map(noteName).join(" ")).toBe(EXPECTED[k]);
    expect(new Set(s.notes.map((n) => n.letter)).size).toBe(6);
    expect(s.notes.every((n) => Math.abs(n.alt) <= 2)).toBe(true);
  });
  it("spells every family in every key without error", () => {
    for (const f of FAMILIES)
      for (const k of KEYS) {
        const modes = f.kind === "rotation" ? 6 : 1;
        for (let m = 0; m < modes; m++) {
          const s = buildScale(k, f.id, m);
          expect(s.error, `${k} ${f.id} mode ${m}`).toBeUndefined();
          expect(s.notes.length).toBe(f.size);
        }
      }
  });
});

/* ── scales against the oracle ─────────────────────────────────────────── */
describe("scale library matches the Python oracle", () => {
  const MAP: Record<string, [string, number]> = {
    major_no4: ["diatonic", 0],
    major_no7: ["diatonic", 3],
    blues: ["blues", 0],
    whole_tone: ["whole", 0],
    prometheus: ["prometheus", 0],
  };
  for (const [key, [famId, mode]] of Object.entries(MAP)) {
    it(`${key} — notes, pcs, prime form and interval vector`, () => {
      const v = (verified.scales as Record<string, any>)[key];
      // major_no7 lives on G when the parent tonic is C
      const tonic = key === "major_no7" ? "C" : "C";
      const s = buildScale(tonic, famId, mode);
      if (key === "major_no7") {
        expect(s.notes.map(noteName).join(" ")).toBe("C D E F G A");
      } else {
        expect(s.notes.map(noteName)).toEqual(v.notes);
      }
      expect(s.pcs.slice().sort((a, b) => a - b)).toEqual(v.pcs);
      expect(s.primeForm).toEqual(v.prime_form);
      expect(s.intervalVector).toEqual(v.interval_vector);
    });
  }
  it("the augmented scale is 6-20 with vector <303630> and no tritones", () => {
    const s = buildScale("C", "aug", 0);
    expect(s.notes.map(noteName)).toEqual(["C", "D#", "E", "G", "Ab", "B"]);
    expect(s.intervalVector).toEqual([3, 0, 3, 6, 3, 0]);
    expect(s.tritones).toBe(0);
  });
});

/* ── THEOREM 4 — available harmony ─────────────────────────────────────── */
describe("Theorem 4 — the harmony is tiny, and chords carry a LIST of names", () => {
  it("the Ionian/Lydian hexatonic has exactly four tertian triads", () => {
    const s = buildScale("C", "diatonic", 0);
    const tri = tertianOnly(findChords(s.notes, [3]));
    expect(tri.map((c) => c.names[0].symbol).sort()).toEqual(["Am", "C", "Em", "G"]);
  });
  it("has exactly three tertian four-note SETS, two of them double-named", () => {
    const s = buildScale("C", "diatonic", 0);
    const tet = tertianOnly(findChords(s.notes, [4]));
    expect(tet.length).toBe(3);
    const labels = tet.map((c) => c.names.map((n) => n.symbol).join("=")).sort();
    expect(labels).toEqual(["C6=Am7", "Cmaj7", "Em7=G6"]);
  });
  it("models a chord as a pitch-class set, so Am7 and C6 are ONE object", () => {
    const s = buildScale("C", "diatonic", 0);
    const c6 = tertianOnly(findChords(s.notes, [4])).find((c) => c.names.some((n) => n.symbol === "C6"))!;
    expect(c6.names.map((n) => n.symbol)).toContain("Am7");
    expect(c6.pcs).toEqual([0, 4, 7, 9]);
  });
  it("the minor hexatonic gives i III v VII", () => {
    const s = buildScale("C", "diatonic", 4);
    const tri = tertianOnly(findChords(s.notes, [3]));
    expect(tri.map((c) => c.names[0].symbol).sort()).toEqual(["Bb", "Cm", "Eb", "Gm"]);
  });
  it("the augmented scale holds 3 major + 3 minor and ZERO dominant 7ths", () => {
    const s = buildScale("C", "aug", 0);
    const all = findChords(s.notes, [3, 4]);
    const syms = all.flatMap((c) => c.names.map((n) => n.symbol));
    const majors = all.filter((c) => c.names.some((n) => /^[A-G][#b]?$/.test(n.symbol)));
    const minors = all.filter((c) => c.names.some((n) => /^[A-G][#b]?m$/.test(n.symbol)));
    expect(majors.length).toBe(3);
    expect(minors.length).toBe(3);
    expect(syms.filter((s2) => /^[A-G][#b]?7$/.test(s2)).length).toBe(0);
    expect(syms.filter((s2) => /^[A-G][#b]?m7$/.test(s2)).length).toBe(0);
  });
});

/* ── THEOREM 5 — skip cycles ───────────────────────────────────────────── */
describe("Theorem 5 — practising 'in thirds' is impossible", () => {
  it("matches the verified skip cycles for the major hexatonic", () => {
    const s = buildScale("C", "diatonic", 0);
    for (const step of [1, 2, 3, 4]) {
      const v = (verified.skip_cycles as any).major_no4[String(step)];
      const c = skipCycle(s.notes, step);
      expect(c.pairs.map((p) => p.interval), `step ${step}`).toEqual(v.intervals);
      expect(c.tally).toEqual(v.tally);
    }
  });
  it("step 2 gives 2 major 3rds, 2 minor 3rds and 2 perfect 4ths", () => {
    const c = skipCycle(buildScale("C", "diatonic", 0).notes, 2);
    expect(c.tally).toEqual({ M3: 2, P4: 2, m3: 2 });
  });
  it("step 3 is perfect on every degree — and the heptatonic is not", () => {
    const hexa = skipCycle(buildScale("C", "diatonic", 0).notes, 3);
    expect(hexa.allPerfect).toBe(true);
    expect(hexa.tally).toEqual({ P5: 3, P4: 3 });

    const hepta = skipCycle(buildDiatonic("C", MAJOR)!, 3);
    expect(hepta.allPerfect).toBe(false);
    expect(hepta.tally.A4).toBe(1);          // F–B breaks the chain
  });
  it("the flawless fourths cycle is unique to the six-note collection", () => {
    expect(skipCycle(buildScale("C", "diatonic", 4).notes, 3).allPerfect).toBe(true);
    expect(skipCycle(buildScale("C", "penta", 0).notes, 2).allPerfect).toBe(false);
    expect(skipCycle(buildDiatonic("C", MAJOR)!, 3).allPerfect).toBe(false);
  });
});

/* ── the resolution solver ─────────────────────────────────────────────── */
describe("resolution solver", () => {
  it("reproduces every row of the verified grid", () => {
    for (const v of verified.resolutions as any[]) {
      const r = solveResolution(
        v.notes_per_cycle, v.subdivision, v.beats_per_bar, v.grouping, "full"
      );
      expect(r.totalNotes, JSON.stringify(v)).toBe(v.total_notes);
      expect(r.bars).toBe(v.bars);
      expect(r.reps).toBe(v.scale_traversals);
    }
  });
  it("the headline numbers hold: hexatonic 16ths resolves far faster than heptatonic", () => {
    const hexa = (g: number) => solveResolution(6, 4, 4, g, "full").bars;
    const hept = (g: number) => solveResolution(7, 4, 4, g, "full").bars;
    expect(hexa(3)).toBe(3);  expect(hept(3)).toBe(21);
    expect(hexa(4)).toBe(3);  expect(hept(4)).toBe(7);
    expect(hexa(5)).toBe(15); expect(hept(5)).toBe(35);
    expect(hexa(6)).toBe(3);  expect(hept(6)).toBe(21);
  });
  it("odd groupings resolve fast in triplets — the live-stream fix", () => {
    expect(solveResolution(6, 3, 4, 5, "full").bars).toBe(5);
    expect(solveResolution(6, 3, 4, 7, "full").bars).toBe(7);
    expect(solveResolution(6, 4, 4, 5, "full").bars).toBe(15); // why NOT to use 16ths
  });
  it("accent mode is never longer than full mode", () => {
    for (const row of resolutionGrid()) {
      const a = solveResolution(row.scaleSize, row.subdivision, 4, row.grouping, "accent");
      const f = solveResolution(row.scaleSize, row.subdivision, 4, row.grouping, "full");
      expect(a.bars).toBeLessThanOrEqual(f.bars);
    }
  });
  it("every resolved bar count is a whole number", () => {
    for (const row of resolutionGrid([5, 6, 7, 8], [2, 3, 4, 6], [3, 4, 5, 6, 7, 9], 1, 4))
      expect(Number.isInteger(row.bars)).toBe(true);
  });
});

/* ── patterns ──────────────────────────────────────────────────────────── */
describe("patterns", () => {
  const s = buildScale("C", "diatonic", 0);
  it("the top note is a real choice with real arithmetic consequences", () => {
    expect(buildPattern("aroha", s.notes, 1, 4, false).length).toBe(6);
    expect(buildPattern("aroha", s.notes, 1, 4, true).length).toBe(7);
    expect(solveResolution(6, 4, 4, 4, "full").bars).toBe(3);
    expect(solveResolution(7, 4, 4, 4, "full").bars).toBe(7);
  });
  it("in-fourths pairs each degree with its perfect fourth or fifth", () => {
    const p = buildPattern("fourths", s.notes, 1, 4, false).map(noteName);
    expect(p.slice(0, 8)).toEqual(["C", "G", "D", "A", "E", "B", "G", "C"]);
  });
  it("cells of 4 run consecutively", () => {
    const p = buildPattern("cells", s.notes, 1, 4, false).map(noteName);
    expect(p.slice(0, 8)).toEqual(["C", "D", "E", "G", "D", "E", "G", "A"]);
  });
  it("every pattern returns notes and never undefined", () => {
    for (const id of ["aroha", "avaroha", "both", "thirds", "fourths", "fifths",
                      "sixths", "cells", "cellsDown", "triads"] as const)
      for (const oct of [1, 2, 3]) {
        const p = buildPattern(id, s.notes, oct, 4, false);
        expect(p.length, id).toBeGreaterThan(0);
        expect(p.every(Boolean), id).toBe(true);
      }
  });
});

/* ── triad pairs ───────────────────────────────────────────────────────── */
describe("triad pairs", () => {
  it("two major triads share no tone at only three interval classes", () => {
    const ok = [];
    for (let i = 1; i < 12; i++) if (triadPair(0, "maj", i, "maj")) ok.push(i);
    expect(ok).toEqual([1, 2, 6, 10, 11]); // m2/M7, M2/m7, tritone
  });
  it("C major + Eb major is NOT a valid pair — they share G", () => {
    expect(triadPair(0, "maj", 3, "maj")).toBeNull();
  });
  it("G + Am is the unique triad pair producing C D E G A B", () => {
    const target = [0, 2, 4, 7, 9, 11].join(",");
    const quals = ["maj", "min", "dim", "aug"] as const;
    const hits: string[] = [];
    for (let a = 0; a < 12; a++) for (const qa of quals)
      for (let b = 0; b < 12; b++) for (const qb of quals) {
        const r = triadPair(a, qa, b, qb);
        if (r && r.join(",") === target) {
          const k = [`${a}${qa}`, `${b}${qb}`].sort().join("+");
          if (!hits.includes(k)) hits.push(k);
        }
      }
    expect(hits).toEqual(["7maj+9min"]); // G major + A minor
  });
  it("the augmented-triad parity rule is complete", () => {
    for (const a of [0, 1, 2, 3] as const)
      for (const b of [0, 1, 2, 3] as const) {
        if (a === b) continue;
        const r = augmentedPair(a, b);
        expect(r.result).toBe(a % 2 === b % 2 ? "whole-tone" : "augmented");
        expect(primeForm(r.pcs)).toEqual(
          a % 2 === b % 2 ? [0, 2, 4, 6, 8, 10] : [0, 1, 4, 5, 8, 9]
        );
      }
  });
});

/* ── the Carnatic layer ────────────────────────────────────────────────── */
describe("Carnatic layer — verified terminology only", () => {
  it("uses the canonical konnakol syllable sets", () => {
    expect(GATIS[3].konnakol).toBe("Ta Ki Ta");
    expect(GATIS[4].konnakol).toBe("Ta Ka Di Mi");
    expect(GATIS[5].konnakol).toBe("Ta Din Gi Na Tom");
    expect(GATIS[7].konnakol).toBe("Ta Ka Di Mi Ta Ki Ta");      // 4+3, not 3+4
    expect(GATIS[9].konnakol).toBe("Ta Ka Di Mi Ta Din Gi Na Tom");
  });
  it("has SIX yatis, and srotovaha is the increasing one", () => {
    expect(YATIS.length).toBe(6);
    expect(YATIS.map((y) => y.id)).toContain("vishama");
    expect(yatiShape("srotovaha")).toEqual([3, 4, 5, 6, 7]);
    expect(yatiShape("gopuccha")).toEqual([7, 6, 5, 4, 3]);
  });
  it("names 6 with no gati (only 3,4,5,7,9 are gatis)", () => {
    expect(GATIS[6].name).toBeNull();
    expect(GATIS[5].name).toBe("Khanda");
  });
});
function yatiShape(id: string) {
  return [...(YATIS.find((y) => y.id === id)!.shape)];
}

/* ── aroha–avaroha ─────────────────────────────────────────────────────── */
describe("aroha–avaroha repeats nothing", () => {
  const s = buildScale("C", "diatonic", 0);          // C D E G A B
  it("plays each note once up and once down, with no doubled turning points", () => {
    const p = buildPattern("both", s.notes, 1, 4, false).map(noteName);
    expect(p).toEqual(["C", "D", "E", "G", "A", "B", "C", "B", "A", "G", "E", "D"]);
  });
  it("never plays the same note twice in a row, including across the loop seam", () => {
    for (let mode = 0; mode < 6; mode++)
      for (const oct of [1, 2]) {
        const sc = buildScale("C", "diatonic", mode);
        const p = buildPattern("both", sc.notes, oct, 4, false);
        for (let i = 0; i < p.length; i++) {
          const next = p[(i + 1) % p.length];        // wraps, so the seam is checked
          expect(pc(p[i]) === pc(next) && p[i].octave === next.octave,
            `mode ${mode} oct ${oct} index ${i}`).toBe(false);
        }
      }
  });
  it("is 2n notes long for an n-note scale over one octave", () => {
    expect(buildPattern("both", s.notes, 1, 4, false)).toHaveLength(12);
    expect(buildPattern("both", buildScale("C", "penta").notes, 1, 4, false)).toHaveLength(10);
  });
  it("is the default drill", async () => {
    const { DEFAULTS } = await import("../src/lib/useDrill");
    expect(DEFAULTS.pattern).toBe("both");
  });
});

/* ── the major blues family (added after the July 2026 audit) ───────────── */
describe("major blues hexatonic", () => {
  it("spells C major blues as C D Eb E G A", () => {
    const s = buildScale("C", "blues-major");
    expect(s.notes.map(noteName)).toEqual(["C", "D", "Eb", "E", "G", "A"]);
  });
  it("spells F major blues as F G Ab A C D", () => {
    const s = buildScale("F", "blues-major");
    expect(s.notes.map(noteName)).toEqual(["F", "G", "Ab", "A", "C", "D"]);
  });
  it("is the same set class as the minor blues, a minor third below", () => {
    const major = buildScale("C", "blues-major");
    const minor = buildScale("A", "blues");
    expect(primeForm(major.pcs)).toEqual(primeForm(minor.pcs));
    expect(new Set(major.pcs)).toEqual(new Set(minor.pcs));
    expect(major.forte).toContain("6-Z47");
  });
  it("spells in every standard key without failure", () => {
    for (const k of KEYS) expect(buildScale(k, "blues-major").error).toBeUndefined();
  });
});

/* ── janta and the arpeggio ladder (July 2026 additions) ────────────────── */
describe("janta and chordLadder patterns", () => {
  const scale = buildScale("C", "diatonic", 0).notes;   // C D E G A B
  it("janta doubles every note of the up-and-down contour", () => {
    const both = buildPattern("both", scale, 1, 4, false);
    const janta = buildPattern("janta", scale, 1, 4, false);
    expect(janta.length).toBe(both.length * 2);
    for (let i = 0; i < both.length; i++) {
      expect(noteName(janta[2 * i])).toBe(noteName(both[i]));
      expect(noteName(janta[2 * i + 1])).toBe(noteName(both[i]));
    }
  });
  it("arpeggiates the four REAL triads of the hexachord, by degree", () => {
    const run = buildPattern("chordLadder", scale, 1, 4, false).map(noteName);
    expect(run).toEqual([
      "C", "E", "G",     // I
      "E", "G", "B",     // iii
      "G", "B", "D",     // V
      "A", "C", "E",     // vi
    ]);
  });
});
